Repository Slemanof/easyeats.live, pull requests merged in 2020-04, with the labels that each got.

#41 Restaurant data mysql fixed location
  .github/workflows/blank.yml
  .gitignore
  data-restaurant-outline.json
  err_handling.py
  insertionMysql.py
  requirements.txt
  restaurant_recommender.sql
  update_menu.py
  zomato_api_without_location_details.py
Labels: Data, must

#44 Creates license
  LICENSE
Labels: documentation

#48 Creates CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#53 047 opening hours
  insertionMysql.py
  readtimigs.py
  restaurant_recommender.sql
  zomato_api_without_location_details.py
Labels: Data, should

#64 045 empty menus
  input_validation.py
  insertionMysql.py
  readtimigs.py
  restaurant_recommender.sql
  zomato_api_without_location_details.py
Labels: Data, should
