Repository Slemanof/easyeats.live, pull requests merged in 2020-05, with the labels that each got.

#65 063 database tweaks
  insertionMysql.py
  restaurant_recommender.sql
  zomato_api_without_location_details.py
Labels: Data, should

#70 019 user database
  insert_user.py
  restaurant_recommender.sql
  zomato_api_without_location_details.py
Labels: Data, should

#77 075 opening hours json
  insertionMysql.py
  readtimigs.py
  restaurant_recommender.sql
Labels: Data, should

#79 076 menu in json
  err_handling.py
  input_validation.py
  menu_checker.py
  restaurant_recommender.sql
  zomato_api_without_location_details.py
Labels: Data, must

#83 081 changed boolean to tinyint
  restaurant_recommender.sql
Labels: Data

#80 069 partial phone numbers
  zomato_api_without_location_details.py
Labels: Data

#90 085 readtimings test
  readtimigs.py
  test/__init__.py
  test/test_readtimings.py
  tests/__init__.py
  tests/test_readtimings.py
Labels: Data, should

#94 092 Usual menu presentation
  .idea/workspace.xml
  flask_application/templates/index.html
Labels: Front-end, must

#101 Adding 2 tests
  CONTRIBUTING.md
  README.md
  security_checklist.md
  tests/test_api_response.py
  tests/test_database.py
Labels: Testing

#104 103 update database
  restaurant_recommender.sql
Labels: Data

#96 078 fix menu updater
  update_menu.py
Labels: Data, should

#108 107 fix email password
  restaurant_recommender.sql
Labels: Data, bug

#105 017 recommendations (backup version)
  flask_application/app.py
  flask_application/templates/index.html
Labels: Back-end, Front-end, should

#117 074 hide unavailable information on page
  flask_application/.idea/flask_application.iml
  flask_application/.idea/inspectionProfiles/Project_Default.xml
  flask_application/.idea/inspectionProfiles/profiles_settings.xml
  flask_application/.idea/misc.xml
  flask_application/.idea/modules.xml
  flask_application/.idea/vcs.xml
  flask_application/.idea/workspace.xml
  flask_application/templates/index.html
Labels: Front-end, must

#127 126 adapt frontend for cuisines in database
  flask_application/templates/index.html
Labels: Front-end

#130 102 keep users checks
  flask_application/static/css/style.css
  flask_application/static/js/filter.js
  flask_application/static/js/filterOpen.js
  flask_application/static/js/restCard.js
  flask_application/templates/index.html
Labels: Front-end

#131 88 display daily menu and opening hours
  flask_application/static/css/style.css
  flask_application/templates/index.html
Labels: Front-end

#123 095 flask login infrastructure
  flask_application/.idea/.gitignore
  flask_application/.idea/flask_application.iml
  flask_application/.idea/misc.xml
  flask_application/.idea/workspace.xml
  flask_application/app.py
  flask_application/static/css/style.css
  flask_application/static/img/SVG/play3.svg
  flask_application/static/img/sprite.svg
  flask_application/static/js/login.js
  flask_application/static/js/logout.js
  flask_application/static/js/redirect.js
  flask_application/static/js/signup.js
  flask_application/templates/index.html
  flask_application/templates/login.html
  flask_application/templates/redirect.html
  flask_application/templates/signup.html
  requirements.txt
Labels: Back-end, Front-end, should

#135 Develop
  README.md
  requirements.txt
  tests/test_api_response.py
  tests/test_database.py
  tests/test_zomato.py
Labels: Testing
